Added collections to everyone
TraceLosu/HoloItems pull request #1
Opened 2022-01-31 17:10 UTC by SpaceNerden

TODO: Change placeholder paper icon

2022-01-31 17:58 UTC, dlee13 commented
You used the old base64 textures which are broken. The base64 values should be copied from this repo: https://github.com/ShiroBlank/HoloItems

2022-01-31 19:02 UTC, dlee13 requested changes
I've commented on everything that needs to be fixed.

Also, most of jp gen 6 is missing, but the original HoloItems repo didn't have them, so I understand you don't know what to put for those. We can add those later.

2022-02-01 01:21 UTC, SpaceNerden commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/lazy.py
> +from cgitb import text
woops

2022-02-01 03:00 UTC, SpaceNerden commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/misc/AChan.java
> +        return Component.text("AChan")
~~No one needs to know~~

2022-02-01 03:09 UTC, SpaceNerden reviewed
Fixed

2022-02-01 04:28 UTC, TraceLosu commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/en1/IRyS.java
> +    private static final String base64 = "ewogICJ0aW1lc3RhbXAiIDogMTYyNjI2NzA0OTc4MywKICAicHJvZmlsZUlkIiA6ICIyMWUzNjdkNzI1Y2Y0ZTNiYjI2OTJjNGEzMDBhNGRlYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJHZXlzZXJNQyIsCiAgI
@SpaceNerden I think you forgot this on your base64 fix commit?

2022-02-01 04:36 UTC, TraceLosu commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/gen0/AZKi.java
> +    private static final String base64 = "ewogICJ0aW1lc3RhbXAiIDogMTYyMDE4NDMxMTEzNSwKICAicHJvZmlsZUlkIiA6ICIwMzFmZDg3ZTgzYTQ0M2FkYWY2MjcxYTNlNGRjNWIzNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJBWktpXyIsCiAgInNpZ
@SpaceNerden You forgot this one too.

2022-02-01 05:02 UTC, TraceLosu requested changes

2022-02-01 05:02 UTC, TraceLosu commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/stars1/Arurandeisu.java
> +    private static final String base64 = "ewogICJ0aW1lc3RhbXAiIDogMTYyNDg3MzE2Nzk3MSwKICAicHJvZmlsZUlkIiA6ICI2Mzk3ZWE2NTVkNzE0YTZmYmE2OGM0MzE0OTQxODA5OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJBcnVyYW5kZWlzdSIsC
Wrong base64

2022-02-01 05:03 UTC, dlee13 requested changes
Some base64 strings to fix, Roboco's name, and delete lazy.py

2022-02-01 05:03 UTC, dlee13 commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/stars1/Arurandeisu.java
> +    private static final String base64 = "ewogICJ0aW1lc3RhbXAiIDogMTYyNDg3MzE2Nzk3MSwKICAicHJvZmlsZUlkIiA6ICI2Mzk3ZWE2NTVkNzE0YTZmYmE2OGM0MzE0OTQxODA5OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJBcnVyYW5kZWlzdSIsC
Fix this

2022-02-01 05:25 UTC, SpaceNerden commented
Done

2022-02-01 05:36 UTC, dlee13 reviewed
The final thing is A-chan's base64, but I will fix that and then merge. Thank you!

2022-02-01 05:36 UTC, dlee13 commented on src/main/java/xyz/holocons/mc/holoitemsrevamp/collection/misc/Achan.java
> +    private static final String base64 = "ewogICJ0aW1lc3RhbXAiIDogMTYyMDE4NTgyMzQ3NCwKICAicHJvZmlsZUlkIiA6ICIzMGQ5MGQ1MGQzZjQ0NzZhOTIyMTZmMDM4OGEzYTlkZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJhY2hhbl9VR0EiLAogI
```suggestion
    private static final String base64 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTA0OGQ2ZGFlZWI4MDgyNjlhZmY1MzMzNzI0YWY4Y2Y4NTY1NmI5MjM2MGI0NTM1M2FmZjcyZWNhMmIwYzZkNiJ9fX0=";
```

2022-02-01 05:45 UTC, dlee13 approved these changes

2022-02-01 05:47 UTC, merged